name: MC2048
author: StealingDaPenta
main: io.stealingdapenta.mc2048.MC2048
version: 1.2.0
description: Play 2048 in MC :)
api-version: 1.21

commands:
  2048:
    description: Launch a new game.
    usage: /<command>

  2048top:
    description: Check out the top 10 best players!
    usage: /<command>

  2048reload:
    description: Reload the configuration file without having to reboot the server.
    usage: /<command>

  2048help:
    description: Show the legend and general information.
    usage: /<command>

permissions:
  mc2048.reload:
    description: Allow usage of /config
    default: op