name: MC2048
author: StealingDaPenta
main: io.stealingdapenta.mc2048.MC2048
version: 1.0
description: Play 2048 in MC :)
api-version: 1.20

commands:
  2048:
    description: Launch a new game.
    usage: /<command>