name: MC2048
author: StealingDaPenta
main: io.stealingdapenta.mc2048.MC2048
version: 1.1.1
description: Play 2048 in MC :)
api-version: 1.21

commands:
  2048:
    description: Launch a new game.
    usage: /<command>

  top2048:
    description: Check out the top 10 best players!
    usage: /<command>
    aliases:
      - 2048top
      - hiscore2048
      - 2048hiscore
      - 2048score
      - score2048

  reload:
    description: Reload the configuration file without having to reboot the server.
    usage: /<command>
    aliases: [ config, load, restart ]

permissions:
  mc2048.reload:
    description: Allow usage of /config
    default: op