name: MC2048
author: StealingDaPenta
main: io.stealingdapenta.mc2048.MC2048
version: 1.0.1
description: Play 2048 in MC :)
api-version: 1.20

commands:
  2048:
    description: Launch a new game.
    usage: /<command>

  top2048:
    description: Check out the top 10 best players!
    usage: /<command>
    aliases:
      - 2048top
      - hiscore2048
      - 2048hiscore
      - 2048score
      - score2048